export type ExplanationSet = { A: string; B: string; C: string; D: string };
export const EXPLANATIONS: Record<string, Record<number, ExplanationSet>> = {
  p46: {
    1: { A: "ทิศเหนือ — ดวงอาทิตย์ไม่ขึ้นทางนี้", B: "ดวงอาทิตย์ขึ้นทางตะวันออกทุกเช้า ✓", C: "ทิศใต้ — ดวงอาทิตย์ไม่ขึ้นทางนี้", D: "ทิศตะวันตก — ดวงอาทิตย์ตกทางนี้ ไม่ใช่ขึ้น" },
    2: { A: "Bedroom ห้องนอน — ใช้นอน ไม่ใช่ทำอาหาร", B: "Bathroom ห้องน้ำ — ใช้อาบน้ำ ไม่ใช่ทำอาหาร", C: "Kitchen ห้องครัว — สถานที่ทำอาหาร ✓", D: "Garden สวน — อยู่นอกบ้าน ไม่ใช่ทำอาหาร" },
    3: { A: "Cap หมวก — ไม่ช่วยให้ร่างกายอบอุ่นเพียงพอ", B: "Sandals รองเท้าแตะ — เหมาะอากาศร้อน ไม่ใช่หนาว", C: "Jacket แจ็คเก็ต — ช่วยให้ร่างกายอบอุ่นในอากาศเย็น ✓", D: "Dress ชุดกระโปรง — ไม่ช่วยให้อบอุ่น" },
    4: { A: "Happy สุขใจ — ตรงข้ามกับการทำของรักหาย", B: "Excited ตื่นเต้น — ความรู้สึกบวก ไม่เหมาะ", C: "Proud ภูมิใจ — ความรู้สึกบวก ไม่เหมาะ", D: "Upset เสียใจ/อารมณ์เสีย — เหมาะกับการทำของรักหาย ✓" },
    5: { A: "Eat กิน — ใช้กับอาหาร ไม่ใช่ของเหลว", B: "Drink ดื่ม — ใช้กับของเหลวเช่นน้ำ ✓", C: "Touch แตะ — ไม่มีความหมายในบริบทนี้", D: "Smell ดมกลิ่น — ไม่เกี่ยวกับการดื่มน้ำ" },
    6: { A: "Light แสง — ไม่ใช่เสียง ไม่ตรงกับ 'loud'", B: "Music เสียงเพลง — เป็นเสียงดังที่ทำให้นอนไม่หลับ ✓", C: "Smell กลิ่น — ไม่ตรงกับ loud (ดัง)", D: "Colour สี — ไม่ใช่เสียง ไม่ตรงกับ loud" },
    7: { A: "Brush — ต้องเติม -s เพราะประธานเป็น She", B: "Brushes — She + กริยาปัจจุบันต้องเติม -s ✓", C: "Brushed — Past Simple ไม่เหมาะกับ 'every morning'", D: "Brushing — ต้องมี is นำหน้า" },
    8: { A: "Watch — Present Simple ขัดแย้งกับ 'last night'", B: "Watches — 3rd person singular ไม่ตรงกับ We", C: "Watching — ต้องมี were นำหน้า", D: "Watched — 'last night' บ่งชี้ Past Simple ✓" },
    9: { A: "Sleep — Present Simple ไม่เหมาะกับ 'right now'", B: "Slept — Past Simple ขัดแย้งกับ 'right now'", C: "Is sleeping — 'right now' + 'Look!' ชี้ว่าใช้ Present Continuous ✓", D: "Sleeps — Present Simple ไม่แสดงการกระทำที่กำลังเกิดขึ้น" },
    10: { A: "Do you help? — ไม่ใช่การขอความช่วยเหลือ", B: "Are you help? — ไวยากรณ์ผิด", C: "Can you...? — ใช้ขอความช่วยเหลืออย่างสุภาพ ✓", D: "Have you help? — ไวยากรณ์ผิด" },
    11: { A: "Am — ใช้กับ I เท่านั้น", B: "Is — ใช้กับเอกพจน์ แต่ students เป็นพหูพจน์", C: "Are — There are + พหูพจน์ (many students) ✓", D: "Be — ไม่ใช่กริยาแท้ที่ถูกต้องในประโยคนี้" },
    12: { A: "Pets — พหูพจน์ถูกต้องของ pet (สัตว์เลี้ยง) ✓", B: "Pet — เอกพจน์ ขัดแย้งกับ two", C: "Petes — ไม่ใช่คำภาษาอังกฤษ", D: "Petting — Gerund ไม่ใช่คำนาม" },
    13: { A: "Already — ใช้กับประโยคบอกเล่า (has already finished)", B: "Yet — ใช้กับ Present Perfect ปฏิเสธ (has not...yet) ✓", C: "Still — วางตำแหน่งต่างออกไป (She still hasn't finished)", D: "Just — ใช้กับประโยคบอกเล่า (has just finished)" },
    14: { A: "Would — ใช้ใน 2nd conditional (If I had...)", B: "Will — 1st conditional: If + present simple, will + base verb ✓", C: "Shall — ไม่เป็นธรรมชาติในภาษาอังกฤษสมัยใหม่", D: "Should — แสดงความควร ไม่ใช่ conditional" },
    15: { A: "Made — Active voice ขัดแย้งกับ 'by my mother'", B: "Makes — Present Simple ขัดแย้งกับ 'last week'", C: "Is making — Present Continuous ขัดแย้งกับ 'last week'", D: "Was made — Passive Voice Past Simple: was + V3 + by ✓" },
    16: { A: "Then — แล้ว/จากนั้น ไม่ใช่คำเชื่อมเปรียบเทียบ", B: "That — ไม่ใช้กับ comparative", C: "To — ไม่ใช้กับ taller", D: "Than — ใช้กับ comparative (taller than) ✓" },
    17: { A: "Tom อ่านการ์ตูนในวันหยุด ไม่ใช่หลังเลิกเรียน", B: "'loves playing football with his friends after school every day' ✓", C: "ไม่ได้กล่าวถึงการนอนหลับในบทอ่าน", D: "ไม่ได้กล่าวถึงการดูทีวีในบทอ่าน" },
    18: { A: "ไม่ตรงกับบทอ่าน", B: "'he wakes up at six o'clock' ✓", C: "ไม่ตรงกับบทอ่าน", D: "ไม่ตรงกับบทอ่าน" },
    19: { A: "บทอ่านไม่ได้บอกว่า easy", B: "ไม่ได้กล่าวถึงครูในบทอ่าน", C: "'he thinks it is fun and very useful' ✓", D: "ไม่ได้กล่าวถึงเพื่อนในบริบทนี้" },
    20: { A: "Tom เล่นฟุตบอลหลังเลิกเรียน ไม่ใช่วันหยุด", B: "ไม่ได้กล่าวถึงการช้อปปิ้งในบทอ่าน", C: "'helps his mother in the garden and reads comic books' ✓", D: "วันหยุดสุดสัปดาห์ไม่ได้ไปโรงเรียน" },
  },
  m13: {
    1: { A: "Excited ตื่นเต้น — ความรู้สึกบวก ไม่เหมาะกับการเดินทางไกล", B: "Exhausted เหนื่อยมาก — เหมาะกับ 'long journey' ✓", C: "Bored เบื่อ — ไม่ตรงบริบท", D: "Angry โกรธ — ไม่มีสาเหตุโกรธในประโยคนี้" },
    2: { A: "Activity กิจกรรม — กว้างเกิน ไม่ตรงกับ accident", B: "Experience ประสบการณ์ — ไม่ตรงกับ accident", C: "Incident เหตุการณ์ — ตรงกับ accident ✓", D: "Occasion งาน/โอกาส — ไม่เหมาะกับ accident" },
    3: { A: "Steady มั่นคง — ตรงข้ามกับการรีบร้อน", B: "Gradual ค่อยเป็นค่อยไป — ตรงข้ามกับรีบร้อน", C: "Careful รอบคอบ — ขัดแย้งกับ 'without thinking carefully'", D: "Hasty รีบร้อน — ตัดสินใจโดยไม่คิดให้รอบคอบ ✓" },
    4: { A: "Combine รวมกัน — ไม่เหมาะกับบริบทนี้", B: "Compare เปรียบเทียบ — ไม่ตรงบริบท", C: "Consider พิจารณา/คิดทบทวน — เหมาะกับการตรวจคำตอบ ✓", D: "Complete ทำให้เสร็จ — ไม่ตรงกับ 'carefully'" },
    5: { A: "Construct สร้าง — เหมาะกับการสร้างสวนสาธารณะ ✓", B: "Produce ผลิต — ใช้กับสินค้า ไม่ใช่สถานที่", C: "Perform แสดง — ไม่เหมาะกับการสร้าง", D: "Deliver ส่ง — ไม่เหมาะกับการสร้าง" },
    6: { A: "Blocked ถูกปิดกั้น — ต้นไม้ล้มขวางถนน ✓", B: "Covered ปกคลุม — ไม่ตรงบริบทที่สุด", C: "Filled เต็ม — ใช้กับของเหลว ไม่เหมาะ", D: "Mixed ผสม — ไม่เหมาะกับบริบทนี้" },
    7: { A: "Creative สร้างสรรค์ — ไม่ตรงกับ 'convinced people'", B: "Sensitive อ่อนไหว — ไม่ตรงกับการโน้มน้าวใจ", C: "Persuasive โน้มน้าวใจ — ตรงกับ 'convinced many people' ✓", D: "Productive มีประสิทธิผล — ไม่ตรงกับการพูดโน้มน้าว" },
    8: { A: "Result ผลลัพธ์ — ไม่ใช่สิ่งที่ค้นหา", B: "Conclusion ข้อสรุป — ไม่ใช่วิธีแก้ปัญหา", C: "Decision การตัดสินใจ — ไม่ตรงบริบท", D: "Solution วิธีแก้ปัญหา — 'solution to the problem' ✓" },
    9: { A: "Go — ต้องเติม -s เพราะประธานเป็น She", B: "Going — ต้องมี is นำหน้า", C: "Gone — Past Participle ไม่ใช่ Present Simple", D: "Goes — She + กริยาปัจจุบัน → เติม -s ✓" },
    10: { A: "Do — Present Simple ขัดแย้งกับ 'last night'", B: "Done — Past Participle ต้องมี had นำหน้า", C: "Doing — ต้องมี was นำหน้า", D: "Did — 'last night' บ่งชี้ Past Simple ✓" },
    11: { A: "Played — Past Simple ไม่แสดงการกระทำที่กำลังดำเนินอยู่", B: "Play — Present ขัดแย้งกับบริบทอดีต", C: "Are playing — Present Continuous ขัดแย้งกับ 'started to rain' (past)", D: "Were playing — Past Continuous: กระทำที่ดำเนินอยู่เมื่อมีเหตุการณ์อื่นเกิด ✓" },
    12: { A: "Go — ไม่ใช่ Past Participle", B: "Went — Past Simple ไม่ใช่ Present Perfect", C: "Gone to = ไปแล้วยังไม่กลับ; Been to = เคยไปแล้วกลับมาแล้ว", D: "Been to — แสดงประสบการณ์ใน Present Perfect ✓" },
    13: { A: "Would — ใช้ใน 2nd conditional (If + past)", B: "Will — 1st conditional: If + present simple → will + base verb ✓", C: "Shall — ไม่เป็นธรรมชาติในภาษาสมัยใหม่", D: "Should — แสดงคำแนะนำ ไม่ใช่ conditional" },
    14: { A: "Took — Active voice ขัดแย้งกับ 'by my grandfather'", B: "Is taking — Present Continuous Active ขัดแย้งกับบริบทอดีต", C: "Has taken — Active Present Perfect ขัดแย้งกับ 'by'", D: "Was taken — Passive Voice Past Simple: was + V3 + by ✓" },
    15: { A: "Don't have to = ไม่จำเป็น ไม่ใช่ห้ามเด็ดขาด", B: "Needn't = ไม่จำเป็น ไม่ใช่ห้าม", C: "Mustn't = ห้ามเด็ดขาด ตรงกับ 'strictly forbidden' ✓", D: "Wouldn't — แสดงความไม่เต็มใจ ไม่ใช่กฎห้าม" },
    16: { A: "Wish + can ไม่ถูกต้อง ต้องใช้ past form", B: "Wish + will ไม่ถูกต้อง", C: "Would ใช้กับ wish + action ไม่ใช่ ability", D: "Could — Wish + could แสดงความต้องการที่ทำไม่ได้ในปัจจุบัน ✓" },
    17: { A: "ขาด had — ต้องเป็น Past Perfect", B: "Present Perfect ขัดแย้งกับ 'arrived' (past)", C: "Had already started — Past Perfect: เกิดก่อนเหตุการณ์อื่นใน past ✓", D: "Past Continuous ไม่เหมาะกับบริบทนี้" },
    18: { A: "Suggest + to-infinitive ไม่ถูกต้อง", B: "Done — Past Participle ไม่เหมาะ", C: "Go — ไม่ถูกต้องทางไวยากรณ์", D: "Doing — Suggest + gerund ✓" },
    19: { A: "Make + object + to-infinitive ไม่ถูกต้อง", B: "Make + object + gerund ไม่ถูกต้อง", C: "Done — Past Participle ไม่เหมาะ", D: "Do — Make + object + bare infinitive (without to) ✓" },
    20: { A: "She passed — ไม่มี inversion หลัง Not only", B: "Passed she — subject-verb ผิด", C: "Did she pass — Inversion: Not only + auxiliary + subject + verb ✓", D: "She did pass — ไม่มี inversion ที่ถูกต้อง" },
    21: { A: "ไม่ตรงกับบทอ่าน", B: "'beautiful temples, delicious street food, and warm, friendly people' ✓", C: "ไม่ได้กล่าวถึงในบทอ่าน", D: "ไม่ได้กล่าวถึงในบทอ่าน" },
    22: { A: "นี่คือ Chiang Mai ไม่ใช่ Bangkok", B: "'modern shopping malls, vibrant night markets, and impressive royal palaces' ✓", C: "เป็นข้อมูล Thailand ทั่วไป ไม่ใช่เฉพาะ Bangkok", D: "ไม่ได้กล่าวถึงสำหรับ Bangkok" },
    23: { A: "นี่คือ Bangkok ไม่ใช่ Chiang Mai", B: "Chiang Mai มีอากาศเย็นกว่า ตรงข้ามกับ hot", C: "'ancient temples...and the cooler weather' ✓", D: "เป็นข้อมูล Thailand ทั่วไป" },
    24: { A: "ไม่สมเหตุสมผล", B: "'foreigners travel there for high-quality but affordable healthcare' ✓", C: "ไม่ตรงบริบท", D: "ไม่ตรงความหมาย" },
    25: { A: "ไม่ใช่ข้อความหลัก", B: "ตรงข้ามกับสิ่งที่บทอ่านบอก", C: "'Thailand offers something wonderful for every type of traveller' ✓", D: "ไม่ใช่ข้อความหลัก" },
  },
  m46: {
    1: { A: "Competition การแข่งขัน — ไม่เหมาะกับ 'met with'", B: "Opposition การต่อต้าน — 'met with opposition' ✓", C: "Exhibition การแสดง — ไม่เกี่ยวข้อง", D: "Recognition การยอมรับ — ตรงข้ามกับความหมายที่ต้องการ" },
    2: { A: "Evident ชัดเจน — ไม่ใช่ adjective สำหรับการพูด", B: "Frequent บ่อยครั้ง — ไม่เหมาะกับ speech ครั้งเดียว", C: "Eloquent พูดได้ไพเราะ/ชัดเจน — เหมาะกับ 'lasting impression' ✓", D: "Relevant เกี่ยวข้อง — ไม่บ่งชี้คุณภาพของการพูด" },
    3: { A: "Setbacks อุปสรรค/ความล้มเหลวชั่วคราว — 'Despite setbacks...managed' ✓", B: "Drawbacks ข้อเสีย — ไม่ตรงบริบทที่สุด", C: "Cutbacks การลดงบ — ไม่เหมาะ", D: "Paybacks การตอบแทน — ไม่เหมาะ" },
    4: { A: "Conventional ตามแบบแผน — ตรงข้ามกับการเปลี่ยนแปลงครั้งใหญ่", B: "Evolutionary ค่อยๆ พัฒนา — ไม่ตรงกับ 'fundamentally changed'", C: "Traditional ดั้งเดิม — ตรงข้ามกับการค้นพบใหม่", D: "Revolutionary ปฏิวัติ — เปลี่ยนแปลงอย่างสิ้นเชิง ✓" },
    5: { A: "Exposure การเผชิญ — ไม่ตรงกับ 'calmly'", B: "Enclosure การล้อมรั้ว — ไม่เกี่ยวข้อง", C: "Composure ความสงบนิ่ง — ตรงกับ 'calmly and professionally' ✓", D: "Disclosure การเปิดเผยข้อมูล — ไม่เหมาะ" },
    6: { A: "Effective มีประสิทธิภาพ — ไม่ตรงกับ 'criticised'", B: "Selective เลือกเฉพาะส่วนที่เป็นประโยชน์ — ทำให้ถูกวิจารณ์ ✓", C: "Collective รวมกัน — ไม่ตรงบริบท", D: "Reflective สะท้อน — ไม่เหมาะ" },
    7: { A: "Obvious ชัดเจน — ไม่เหมาะกับ strategic expansion", B: "Tedious น่าเบื่อ — ไม่เหมาะกับ strategic decision", C: "Ambitious ทะเยอทะยาน — เหมาะกับการขยายตลาด ✓", D: "Previous ก่อนหน้า — ไม่เหมาะ" },
    8: { A: "Arrival การมาถึง — ไม่เหมาะกับ economy", B: "Survival การอยู่รอด — ไม่ตรงกับ 'encouraging signs'", C: "Interval ช่วงเวลา — ไม่เหมาะ", D: "Revival การฟื้นคืน — ตรงกับ 'after years of stagnation' ✓" },
    9: { A: "Waited — Past Simple ไม่แสดงการกระทำต่อเนื่อง", B: "Have been waiting — Present Perfect ขัดแย้งกับ 'arrived' (past)", C: "Were waiting — Past Continuous ไม่เหมาะกับ 'for over 24 hours'", D: "Had been waiting — Past Perfect Continuous: ต่อเนื่องก่อนจุดหนึ่งใน past ✓" },
    10: { A: "They met — ไม่มี inversion หลัง Not only", B: "Met they — subject-verb ผิด", C: "They did meet — ไม่มี inversion", D: "Did they meet — Inversion: Not only + auxiliary + subject + verb ✓" },
    11: { A: "Will enjoy — ขัดแย้งกับ past condition", B: "Would enjoy — 2nd conditional ไม่ตรงกับ 'Had + V3'", C: "Had enjoyed — ไม่ถูกต้อง", D: "Would have enjoyed — 3rd conditional: Had + V3 → would have + V3 ✓" },
    12: { A: "Completes — 3rd person singular ไม่ใช้กับ Subjunctive", B: "Completed — Past ไม่ใช้กับ Subjunctive", C: "Complete — Subjunctive: insist that + base form ✓", D: "Has completed — Present Perfect ไม่ใช้กับ Subjunctive" },
    13: { A: "Although — ต้องตามด้วย subject + verb ไม่ใช่ noun phrase", B: "However — Adverb ไม่นำหน้า noun phrase", C: "Despite + noun phrase (his lack of...) ✓", D: "Even — ไม่สมบูรณ์ (Even though ต้องตามด้วย clause)" },
    14: { A: "That — ไม่ใช้ใน non-defining relative clause (มี comma)", B: "Who — ใช้กับคน ไม่ใช่ report", C: "What — ไม่ใช้ใน relative clause แบบนี้", D: "Which — non-defining relative clause + ไม่ใช่คน ✓" },
    15: { A: "Slow down ช้าลง — ไม่ตรงกับปัญหาเสียงเบา", B: "Carry on ทำต่อไป — ไม่ตรงบริบท", C: "Speak up พูดเสียงดังขึ้น — ตรงกับ 'spoke so quietly' ✓", D: "Step back ถอยหลัง — ไม่เกี่ยวข้อง" },
    16: { A: "Are verified — Indicative mood ไม่ใช้กับ essential that", B: "Were verified — Past ไม่เหมาะ", C: "Be verified — Passive Subjunctive: essential that + be + V3 ✓", D: "Will be verified — Future ไม่ใช้กับ Subjunctive" },
    17: { A: "The confident — ไม่ถูกโครงสร้าง", B: "More confident — ขาด 'the' ในโครงสร้าง the more...the more", C: "Most confident — Superlative ไม่ตรงโครงสร้าง", D: "The more confident — the more...the more + adjective ✓" },
    18: { A: "Tell — Present ไม่ตรงกับ would rather ในบริบทอดีต", B: "Told — Simple past ใช้กับปัจจุบัน/อนาคตเท่านั้น", C: "Have told — ไม่ถูกต้อง", D: "Had told — would rather + past perfect (เหตุการณ์อดีต) ✓" },
    19: { A: "To be — deny + to-infinitive ไม่ถูกต้อง", B: "To have been — ไม่ถูกต้อง", C: "Being — deny + gerund ✓", D: "Been — ขาด being" },
    20: { A: "We have seen — ไม่มี inversion หลัง Rarely", B: "We saw — ไม่มี inversion", C: "Have we seen — Inversion: Rarely + auxiliary + subject + verb ✓", D: "Did we see — Past Simple ไม่เหมาะ (Rarely ใช้กับ Present Perfect)" },
    21: { A: "ไม่ได้กล่าวถึงในบทอ่าน", B: "'automate complex cognitive tasks once considered exclusively human' ✓", C: "ไม่ใช่ประเด็นหลักของบทอ่าน", D: "ไม่ได้กล่าวถึง" },
    22: { A: "ตรงข้ามกับมุมมองของ proponents", B: "ไม่ตรงกับบทอ่าน", C: "'AI will ultimately create more jobs than it displaces' ✓", D: "ไม่ตรงกับบทอ่าน" },
    23: { A: "ตรงข้ามกับความกังวลของ critics", B: "ไม่ได้กล่าวถึงในบทอ่าน", C: "'the pace of AI development may outstrip society's ability to adapt' ✓", D: "ไม่ได้กล่าวถึง" },
    24: { A: "ไม่ตรงความหมาย", B: "Transferable = ใช้ได้หลายบริบท/สถานการณ์ ✓", C: "ไม่ตรงความหมาย", D: "ไม่ตรงความหมาย" },
    25: { A: "ไม่ตรงกับบทอ่าน", B: "ไม่ได้กล่าวถึงในบทอ่าน", C: "'ensuring that the economic benefits of AI are distributed broadly' ✓", D: "ตรงข้ามกับสิ่งที่บทอ่านบอก" },
  },
};
